=== mifos/head/mifos/src/org/mifos/framework/util/resources/tabletag/tabletag.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.aditi.com" xmlns="http://www.aditi.com"
	elementFormDefault="qualified ">

	<!-- user defined Simple types  -->
	<xs:simpleType name="valuetype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="string" />
			<xs:enumeration value="key" />
			<xs:enumeration value="method" />
			<xs:enumeration value="date" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="columntype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="link"/>
			<xs:enumeration value="text"/>
		</xs:restriction>
	</xs:simpleType>

	<!--Table tag definition -->
	<xs:element name="table">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="path" maxOccurs="unbounded" />
				<xs:element ref="pagerequirements" maxOccurs="1"/>
				<xs:element ref="row" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="class" type="xs:string" />
			<xs:attribute name="resourcebundle" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="path">
		<xs:complexType>
			<xs:attribute name="key" type="xs:string"/>
			<xs:attribute name="action" type="xs:string"/>			
			<xs:attribute name="forwardkey" type="xs:string"/>			
		</xs:complexType>
	</xs:element>
	
	<xs:element name="pagerequirements">
		<xs:complexType>
			<xs:attribute name="numbersrequired" type="xs:boolean" default="true"/>
			<xs:attribute name="headingrequired" type="xs:boolean" default="true"/>
			<xs:attribute name="bluelinerequired" type="xs:boolean" default="true"/>
			<xs:attribute name="valignnumbers" type="xs:boolean" default="true"/>
			<xs:attribute name="blanklinerequired" type="xs:boolean" default="false"/>
			<xs:attribute name="topbluelinerequired" type="xs:boolean" default="true"/>
			<xs:attribute name="bottombluelinerequired" type="xs:boolean" default="false"/>
			<xs:attribute name="flowRequired" type="xs:boolean" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="row">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="column" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="tdrequired" type="xs:boolean"
				default="false" />
			<xs:attribute name="suppressrow" type="xs:boolean"
				default="false" />
		</xs:complexType>
	</xs:element>

	<xs:element name="column">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="displayname" maxOccurs="1" />
				<xs:element ref="parameters" maxOccurs="1" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="label" type="xs:string" use="required"/>
			<xs:attribute name="labeltype" type="valuetype" use="required"/>
			<xs:attribute name="type" type="columntype" use="required"/>
			<xs:attribute name="action" type="xs:string" />
			<xs:attribute name="boldlabel" type="xs:boolean"
				default="false" />
			<xs:attribute name="image" type="xs:boolean" default="false"/>
			<xs:attribute name="islinkoptional" type="xs:boolean" use="optional" default="false"/> 
			<xs:attribute name="checkoptionallinkrequired" type="xs:string" use="optional"/>
			<xs:attribute name="styleClass" type="xs:string" use="optional" default="fontnormalbold"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="displayname">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fragment-name" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="bold" type="xs:boolean" default="false"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="fragment-name">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required" />
			<xs:attribute name="type" type="valuetype" use="required" />
			<xs:attribute name="bold" type="xs:boolean" default="false"/>
			<xs:attribute name="italic" type="xs:boolean" default="false"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parameter" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="parameter">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="valuetype" type="valuetype" use="required"/>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== mifos/head/mifos/src/org/mifos/framework/util/resources/tabletag/groupTransfer.xml
<?xml version="1.0" encoding="UTF-8"?>
<table class="org.mifos.xyz" name="center" resourcebundle="resource"
		xmlns="http://www.aditi.com" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.aditi.com tabletag.xsd ">
<path key="centerSearch" forwardkey="search_success" action="/centerCustAction.do"/> 
<pagerequirements numbersrequired="true" bluelinerequired="true" headingrequired="false" blanklinerequired="false" valignnumbers="true"/>  
  
<row>
	<column label="" labeltype="string" boldlabel="false" type="text" >
		<displayname>
			<fragment-name name="parentOfficeName" type="method"/>
		</displayname>
	</column>
	<column label="/" labeltype="string" boldlabel="true" type="link" action="GroupAction.do" >
		<displayname bold="true">
			<fragment-name name="centerName" type="method"/>
		</displayname>
		<parameters>
			<parameter name="parentOfficeId" value="parentOfficeId" valuetype="method"/>
			<parameter name="centerSystemId" value="centerSystemId" valuetype="method"/>
			<parameter name="centerName" value="centerName" valuetype="method"/>
			<parameter name="method" value="confirmParentTransfer" valuetype="string"/>
		</parameters>
	</column>
</row>
  
</table>

=== mifos/head/mifos/src/org/mifos/framework/util/resources/tabletag/LoanAccount.xml
<?xml version="1.0" encoding="UTF-8"?>
<table class="org.mifos.xyz" name="center" resourcebundle="resource"
		xmlns="http://www.aditi.com" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.aditi.com tabletag.xsd ">
  <path key="customersearch" forwardkey="search_sucess" action="CustomerSearchAction.do"/> 
  <pagerequirements numbersrequired="true" bluelinerequired="false"  blanklinerequired="true" headingrequired="true"/>  
  
  
  
  <row>
  	<column label="Loan" labeltype="key" boldlabel="true" type="link" action="loanAccountAction.do"  styleClass="headingblue">
  		<displayname bold="true">
  			<fragment-name name="Account # " type="string"/>
  			<fragment-name name="loanGlobalAccountNumber" type="method"/>  			
  		</displayname>
  		<parameters>
  			<parameter name="globalAccountNum" value="loanGlobalAccountNumber" valuetype="method"/>
  			<parameter name="method" value="get" valuetype="string"/>
  			<parameter name="recordOfficeId" value="branchGlobalNum" valuetype="method"/>
        	<parameter name="recordLoanOfficerId" value="loanOffcerGlobalNum" valuetype="method"/>
  		</parameters>
  	</column>  	
  </row>
  
  <row>
  	<column label="status" labeltype="key" boldlabel="true" type="text" image="true">
  		<displayname>
  			<fragment-name name="status" type="method"/>
  		</displayname>
  	</column>
  	<column label="loanofficer" labeltype="key" boldlabel="true" type="text">  		
  		<displayname>
  			<fragment-name name="loanOfficerName" type="method"/>
  		</displayname>
  	</column>
  </row>
  
  <row>
    <column label="Client" labeltype="key" boldlabel="false" type="link" action="clientCustAction.do">
      <displayname>
       <fragment-name name="centerName" type="method"/>
       <fragment-name name=": ID " type="string"/>
       <fragment-name name="centerGlobalCustNum" type="method"/>
      </displayname>
      <parameters>
        <parameter name="globalCustNum" value="centerGlobalCustNum" valuetype="method"/>
        <parameter name="method" value="get" valuetype="string"/>
        <parameter name="recordOfficeId" value="branchGlobalNum" valuetype="method"/>
        <parameter name="recordLoanOfficerId" value="loanOffcerGlobalNum" valuetype="method"/>
      </parameters>
    </column>
  </row> 
  
  <row>
	<column label="alsosee" labeltype="key" boldlabel="false" type="link" action="CustomerSearchAction.do">
		<displayname>
			<fragment-name name="branchName" type="method"/>
		</displayname>
		<parameters>
			<parameter name="method" value="load" valuetype="string"/>
		</parameters>
	</column>
	<column label="/" labeltype="string" boldlabel="false" type="link" action="centerCustAction.do">
		<displayname>
			<fragment-name name="clientName" type="method"/>
		</displayname>
		<parameters>
			<parameter name="globalCustNum" value="clientGlobalCustNum" valuetype="method"/>
			<parameter name="method" value="get" valuetype="string"/>
			<parameter name="recordOfficeId" value="branchGlobalNum" valuetype="method"/>
        	<parameter name="recordLoanOfficerId" value="loanOffcerGlobalNum" valuetype="method"/>
		</parameters>
	</column>
	
	<column label="/" labeltype="string" boldlabel="false" type="link" action="GroupAction.do">
		<displayname>
			<fragment-name name="groupName" type="method" />
		</displayname>
		<parameters>
			<parameter name="globalCustNum" value="groupGlobalCustNum" valuetype="method"/>
			<parameter name="method" value="getDetails" valuetype="string"/>
			<parameter name="recordOfficeId" value="branchGlobalNum" valuetype="method"/>
       		<parameter name="recordLoanOfficerId" value="loanOffcerGlobalNum" valuetype="method"/>
		</parameters>
	</column>
	
	</row>
  	
  	
</table>

=== mifos/head/mifos/src/org/mifos/framework/util/resources/tabletag/groupSearch_clientCreate.xml
<?xml version="1.0" encoding="UTF-8"?>
<table class="org.mifos.xyz" name="group" resourcebundle="resource"
		xmlns="http://www.aditi.com" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.aditi.com tabletag.xsd ">
<path key="GroupList" forwardkey="search_success" action="GroupAction.do"/> 
<pagerequirements numbersrequired="true" bluelinerequired="true" headingrequired="false" valignnumbers="false" blanklinerequired="false" bottombluelinerequired="true"/>  
<row>
	<column label="" labeltype="string" boldlabel="false" type="text" >
		<displayname>
			<fragment-name name="officeName" type="method"/>
		</displayname>
	</column>
	<column label="/" labeltype="string" boldlabel="false" type="text" >
		<displayname>
			<fragment-name name="centerName" type="method"/>
		</displayname>
	</column>
	<column label="/" labeltype="string" boldlabel="true" type="link" action="clientCreationAction.do">
		<displayname bold="true">
			<fragment-name name="groupName" type="method"/>
		</displayname>
		<parameters>
			<parameter name="parentGroupId" value="groupId" valuetype="method"/>
			<parameter name="method" value="load" valuetype="string"/>
			<parameter name="isClientUnderGrp" value="1" valuetype="string"/>
		</parameters>
	</column>
</row>
  
</table>

=== mifos/head/mifos/src/org/mifos/framework/util/resources/tabletag/accounts.xml
<?xml version="1.0" encoding="UTF-8"?>
<table class="org.mifos.xyz" name="center" resourcebundle="resource"
		xmlns="http://www.aditi.com" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.aditi.com tabletag.xsd ">
<path key="accountsSearch" forwardkey="search_success" action="AccountsSearchAction.do"/> 
<pagerequirements numbersrequired="true" bluelinerequired="true" headingrequired="false" valignnumbers="false" blanklinerequired="false" bottombluelinerequired="true"/>  
<row>
	<column label="" labeltype="string" boldlabel="false" type="text" >
		<displayname>
			<fragment-name name="officeName" type="method"/>
		</displayname>
	</column>
	
	<column label="/" labeltype="string" boldlabel="true" type="text" >
		<displayname>
			<fragment-name name="centerName" type="method"/>
		</displayname>
	</column>
	<column label="/" labeltype="string" boldlabel="true" type="text">
		<displayname>
			<fragment-name name="groupName" type="method"/>
		</displayname>
		
		<parameters>
			<parameter name="method" value="getPrdOfferings" valuetype="string"/>
			<parameter name="customer.customerId" value="clientId" valuetype="method"/>
			
		</parameters>
		
	</column>
	<column label="/" labeltype="string" boldlabel="true" type="link" action="loanAccountAction.do">
		<displayname bold="true">
			<fragment-name name="clientName" type="method" bold="true"/>
			<fragment-name name=":ID" type="string" bold="true"/>
			<fragment-name name="globelNo" type="method" bold="true"/>
		</displayname>	
		<parameters>
			<parameter name="method" value="getPrdOfferings" valuetype="string"/>
			<parameter name="customer.customerId" value="clientId" valuetype="method"/>
			
		</parameters>
		
	</column>
	
	
	
</row>
  
</table>

=== mifos/head/mifos/src/org/mifos/framework/util/resources/tabletag/center.xml
<?xml version="1.0" encoding="UTF-8"?>
<table class="org.mifos.xyz" name="center" resourcebundle="resource"
		xmlns="http://www.aditi.com" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.aditi.com tabletag.xsd ">
<path key="centerSearch" forwardkey="search_success" action="centerAction.do"/> 
<pagerequirements numbersrequired="true" bluelinerequired="true" headingrequired="false" valignnumbers="false" blanklinerequired="false" bottombluelinerequired="true"/>  
<row>
	<column label="" labeltype="string" boldlabel="false" type="text" >
		<displayname>
			<fragment-name name="parentOfficeName" type="method"/>
		</displayname>
	</column>
	<column label="/" labeltype="string" boldlabel="true" type="link" action="GroupAction.do">
		<displayname bold="true">
			<fragment-name name="centerName" type="method"/>
		</displayname>
		<parameters>
			<parameter name="parentOfficeId" value="parentOfficeId" valuetype="method"/>
			<parameter name="centerSystemId" value="centerSystemId" valuetype="method"/>
			<parameter name="method" value="load" valuetype="string"/>
		</parameters>
	</column>
</row>
  
</table>
