=== mifos/head/questionnaire/src/main/resources/org/mifos/platform/questionnaire/QuestionGroupDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.mifos.org/QuestionGroupDefinition"
        xmlns:tns="http://www.mifos.org/QuestionGroupDefinition" elementFormDefault="qualified">

    <element name="QuestionGroup" type="tns:QuestionGroup"/>

    <complexType name="QuestionGroup">
        <sequence>
            <element name="ppi" type="boolean"/>
            <element name="title" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="editable" type="boolean"/>
            <element name="eventSource" type="tns:EventSource" maxOccurs="unbounded" minOccurs="1"/>
            <element name="section" type="tns:Section" maxOccurs="unbounded" minOccurs="1"/>
        </sequence>
    </complexType>

    <complexType name="EventSource">
        <all>
            <element name="event" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="source" type="string" maxOccurs="1" minOccurs="1"/>
        </all>
        <attribute name="order" type="int" use="required"/>
    </complexType>

    <complexType name="Section">
        <sequence>
            <element name="name" type="string" maxOccurs="1" minOccurs="0"/>
            <element name="question" type="tns:Question" maxOccurs="unbounded" minOccurs="1"/>
        </sequence>
        <attribute name="order" type="int" use="required"/>
    </complexType>

    <complexType name="Question">
        <sequence>
            <element name="title" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="type" type="tns:QuestionType" maxOccurs="1" minOccurs="1"/>
            <element name="minValue" type="int" maxOccurs="1" minOccurs="0"/>
            <element name="maxValue" type="int" maxOccurs="1" minOccurs="0"/>
            <element name="choice" type="tns:QuestionChoice" maxOccurs="unbounded" minOccurs="0"/>
            <element name="mandatory" type="boolean" maxOccurs="1" minOccurs="0"/>
        </sequence>
        <attribute name="order" type="int" use="required"/>
    </complexType>

    <simpleType name="QuestionType">
        <restriction base="token">
            <enumeration value="FREETEXT"/>
            <enumeration value="NUMERIC"/>
            <enumeration value="DATE"/>
            <enumeration value="SINGLE_SELECT"/>
            <enumeration value="MULTI_SELECT"/>
            <enumeration value="SMART_SELECT"/>
        </restriction>
    </simpleType>

    <complexType name="QuestionChoice">
        <sequence>
            <element name="value" type="string" maxOccurs="1" minOccurs="1"/>
            <element name="tag" type="string" maxOccurs="unbounded" minOccurs="0" />
        </sequence>
        <attribute name="order" type="int" use="required"/>
    </complexType>
</schema>

=== mifos/head/questionnaire/src/test/resources/org/mifos/platform/questionnaire/QuestionGroupDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<QuestionGroup xmlns="http://www.mifos.org/QuestionGroupDefinition"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.mifos.org/QuestionGroupDefinition QuestionGroupDefinition.xsd ">
    <ppi>true</ppi>
    <title>PPI India</title>
    <editable>false</editable>
    <eventSource order="1">
        <event>Create</event>
        <source>Loan</source>
    </eventSource>
    <section order="1">
        <name>default</name>
        <question order="1">
            <title>Your DOB</title>
            <type>DATE</type>
        </question>
        <question order="2">
            <title>How many family members</title>
            <type>NUMERIC</type>
            <minValue>3</minValue>
            <maxValue>10</maxValue>
            <mandatory>true</mandatory>
        </question>
    </section>
    <section order="2">
        <name>misc</name>
        <question order="1">
            <title>Father's name'</title>
            <type>FREETEXT</type>
        </question>
        <question order="2">
            <title>No of dependents</title>
            <type>SINGLE_SELECT</type>
            <choice order="1">
                <value>Less than 2</value>
            </choice>
            <choice order="2">
                <value>Less than 5</value>
            </choice>
            <choice order="3">
                <value>Less than 10</value>
            </choice>
            <mandatory>true</mandatory>
        </question>
        <question order="3">
            <title>Previous Loans taken for</title>
            <type>SMART_SELECT</type>
            <mandatory>true</mandatory>
            <choice order="1">
                <value>No Product</value>
                <tag>Never</tag>
            </choice>
            <choice order="2">
                <value>Product 1</value>
                <tag>Agriculture</tag>
            </choice>
            <choice order="3">
                <value>Product 2</value>
                <tag>Fishing</tag>
                <tag>Farming</tag>
            </choice>
            <choice order="4">
                <value>Product 3</value>
                <tag>Construction</tag>
            </choice>
        </question>
    </section>
</QuestionGroup>
